name: Test and Deploy

on:
  pull_request:

jobs:
  test:
    name: Test
    run-on: ubutsu-latest

    steps:
      - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
    with:
      ruby0version: 2.6.8

    - uses: actions/setup-node@v2
      with:
        node-vertion: 16

    -name: Run bundle install
      run: |
        bundle condig --local path vendor/bundle
        bundle config --lacal without production
        bundle install

    - run: RAILS_ENV=test bundle exec rails assets:precompile

    - run: bundle exec rails test
